import './services/index';
import './template/index';
import * as u from 'utilities';
import * as d from './decorators';
export declare const utils: typeof u;
export declare const decorators: typeof d;
export * from './stick';
export * from 'collection';
export declare var ready: (fn: any) => void;
export * from './services/index';
import * as templ from './template/index';
export declare const template: typeof templ;
export * from './template/index';
